isnextto(member(Office1,_),member(Office2,_),Offices):-
    nextto(Office1,Office2,Offices).
isnextto(member(Office1,_),member(Office2,_),Offices):-
    nextto(Office2,Office1,Offices).

solve_puzzle(Answer1,Answer2,Workplace):-
    Workplace = [
        office(1,Department1,Colour1,Computer1,Drink1,Phone1),
        office(2,Department2,Colour2,Computer2,Drink2,Phone2),
        office(3,Department3,Colour3,Computer3,Drink3,Phone3),
        office(4,Department4,Colour4,Computer4,Drink4,Phone4),
        office(5,Department5,Colour5,Computer5,Drink5,Phone5)],
    member(office(_,"ÐëçñïöïñéêÞ","Êüêêéíï",_,_,_),Workplace),
    member(office(_,"ÏñãÜíùóç êáé Äéïßêçóç",_,"Macbook Pro",_,_),Workplace),
    member(office(_,_,"ÐñÜóéíï",_,"ÊáöÝò",_),Workplace),
    member(office(_,"Ïéêïíïìéêü",_,_,"ÔóÜé",_),Workplace),
    member(office(_,_,"Ìðåæ",_,_,_),Workplace),
    member(office(_,_,"ÐñÜóéíï",_,_,_),Workplace),
    nextto(office(_,_,"Ìðåæ",_,_,_),
           office(_,_,"ÐñÜóéíï",_,_,_),
           Workplace),
    member(office(_,_,_,"Macbook Air",_,"iPhone"),Workplace),
    member(office(_,_,"Êßôñéíï",_,_,"Blackberry"),Workplace),
    member(office(3,_,_,_,"ÃÜëá",_),Workplace),
    member(office(1,"Äéåèíåßò Ó÷Ýóåéò",_,_,_,_),Workplace),
    isnextto(member(office(_,_,_,_,_,"Nokia"),Workplace),
             member(office(_,_,_,"Netbook",_,_),Workplace),
             Workplace),
    isnextto(member(office(_,_,_,_,_,"Blackberry"),Workplace),
             member(office(_,_,_,"Windows 7",_,_),Workplace),
             Workplace),
    member(office(_,_,_,_,"ÐïñôïêáëÜäá","Android"),Workplace),
    member(office(_,"Ðñïìçèåéþí",_,_,_,"Ericsson"),Workplace),
    isnextto(member(office(_,"Äéåèíåßò Ó÷Ýóåéò",_,_,_,_),Workplace),
             member(office(_,_,"Ìðëå",_,_,_),Workplace),
             Workplace),
    member(office(_,Answer1,_,_,"Íåñü",_),Workplace),
    member(office(_,Answer2,_,"Windows XP",_,_),Workplace).

%    member(office(_,ðëçñïöïñéêÞ,êüêêéíï,_,_,_),Workplace),
%    member(office(_,ïñãÜíùóç_êáé_äéïßêçóç,_,macbook_pro,_,_),Workplace),
%    member(office(_,_,ðñÜóéíï,_,êáöÝò,_),Workplace),
%    member(office(_,ïéêïíïìéêü,_,_,ôóÜé,_),Workplace),
%    member(office(_,_,_,macbook_air,_,iPhone),Workplace),
%    member(office(_,_,êßôñéíï,_,_,blackberry),Workplace),
%    member(office(3,_,_,_,milk,_),Workplace),
%    member(office(1,äéåèíåßò_ó÷Ýóåéò,_,_,_,_),Workplace),
%    member(office(_,_,_,_,ðïñôïêáëÜäá,android),Workplace),
%    member(office(_,ðñïìçèåéþí,_,_,_,ericsson),Workplace),
%    member(office(L,_,ìðåæ,_,_,_),Workplace),
%    member(office(R,_,ðñÜóéíï,_,_,_),Workplace), nextto(L,R,Workplace),
%    member(office(OfficeA,_,_,_,_,nokia),Workplace),
%    member(office(OfficeB,_,_,netbook,_,_),Workplace),
%    isnextto(OfficeA,OfficeB,Workplace),
%    member(office(OfficeC,_,_,_,_,blackberry),Workplace),
%    member(office(OfficeD,_,_,windows_7,_,_),Workplace),
%    isnextto(OfficeC,OfficeD,Workplace),
%    member(office(OfficeE,äéåèíåßò_ó÷Ýóåéò,_,_,_,_),Workplace),
%    member(office(OfficeF,_,ìðëå,_,_,_),Workplace),
%    isnextto(OfficeE,OfficeF,Workplace),
%    member(office(_,Answer1,_,_,íåñü,_),Workplace),
%    member(office(_,Answer2,_,windows_xp,_,_),Workplace).
